// ßâ×ßâáßâØßâößâÑßâóßâÿ ßâößâÑßâíßâÖßâÜßâúßâûßâÿßâúßâáßâÉßâô Whykthor GSV-ßâÿßâí ßâøßâÿßâößâá ßâ¿ßâößâÿßâÑßâøßâ£ßâÉ.
export const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: 'dashboard.view',
  STUDENTS_READ: 'students.read',
  STUDENTS_READ_SELF: 'students.read.self',
  STUDENTS_WRITE: 'students.write',
  TEACHERS_READ: 'teachers.read',
  TEACHERS_WRITE: 'teachers.write',
  CLASSES_READ: 'classes.read',
  CLASSES_WRITE: 'classes.write',
  SUBJECTS_READ: 'subjects.read',
  SUBJECTS_WRITE: 'subjects.write',
  GRADES_READ: 'grades.read',
  GRADES_WRITE: 'grades.write',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_WRITE: 'attendance.write',
  ASSIGNMENTS_READ: 'assignments.read',
  ASSIGNMENTS_WRITE: 'assignments.write',
  CALENDAR_READ: 'calendar.read',
  TEACHER_CALENDAR_VIEW: 'teacher_calendar.view',
  TEACHER_CALENDAR_MANAGE_ALL: 'teacher_calendar.manage.all',
  SCHEDULES_MANAGE: 'schedules.manage',
  SCHEDULES_RESPOND: 'schedules.respond',
  SCHEDULES_VIEW: 'schedules.view',
  SCHEDULES_PUBLISH: 'schedules.publish',
  SCHEDULES_AUDIT: 'schedules.audit',
  MESSAGES_READ: 'messages.read',
  MESSAGES_WRITE: 'messages.write',
  MESSAGES_WRITE_OWN_CLASS: 'messages.write.own_class',
  LIBRARY_READ: 'library.read',
  LIBRARY_WRITE: 'library.write',
  LIBRARY_LOANS_READ: 'library_loans.read',
  LIBRARY_LOANS_WRITE: 'library_loans.write',
  REPORTS_VIEW: 'reports.view',
  OCCURRENCES_READ: 'occurrences.read',
  OCCURRENCES_WRITE: 'occurrences.write',
  DIARY_WRITE: 'diary.write',
  LESSON_PLANS_WRITE: 'lesson_plans.write',
  GOALS_MANAGE_SELF: 'goals.manage.self',
  GOALS_READ_ALL: 'goals.read.all',
  TEACHER_PORTAL_VIEW: 'teacher_portal.view',
  GUARDIAN_PORTAL_VIEW: 'guardian_portal.view',
  ACADEMIC_RECORD_VIEW: 'academic_record.view',
  REGISTRATION_VIEW: 'registration.view',
  ENROLLMENTS_MANAGE: 'enrollments.manage',
  USERS_MANAGE: 'users.manage',
  USERS_MANAGE_ADMINISTRATIVE: 'users.manage.administrative',
  SETTINGS_READ: 'settings.read',
  SETTINGS_WRITE: 'settings.write',
  AUDIT_READ: 'audit.read',
  EVENTS_WRITE: 'events.write',
  SUBMISSIONS_READ_ALL: 'submissions.read.all',
  SUBMISSIONS_GRADE: 'submissions.grade',
  SYSTEM_EXPORT: 'system.export',
  DIRECT_CHAT_USE: 'direct_chat.use',
  CALLS_USE: 'calls.use',
  INTERNSHIPS_READ: 'internships.read',
  INTERNSHIPS_READ_SELF: 'internships.read.self',
  INTERNSHIPS_WRITE: 'internships.write',
  INTERNSHIP_COMPANIES_READ: 'internship_companies.read',
  INTERNSHIP_COMPANIES_WRITE: 'internship_companies.write',
  TCC_READ: 'tcc.read',
  TCC_READ_SELF: 'tcc.read.self',
  TCC_WRITE: 'tcc.write',
  LABORATORIES_READ: 'laboratories.read',
  LABORATORIES_WRITE: 'laboratories.write',
  COURSES_READ: 'courses.read',
  COURSES_WRITE: 'courses.write',
  CERTIFICATES_READ: 'certificates.read',
  CERTIFICATES_WRITE: 'certificates.write',
  SCHOOL_CALENDAR_VIEW: 'school_calendar.view',
  STUDENT_ENROLLMENT: 'student_enrollment',
});

export const ADMINISTRATIVE_PROFILE_TYPES = Object.freeze([
  'secretario',
  'coordenador',
  'administrador',
]);

const ROLE_PERMISSION_MATRIX = Object.freeze({
  aluno: Object.freeze([
    PERMISSIONS.STUDENTS_READ_SELF,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.CALENDAR_READ,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_WRITE_OWN_CLASS,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.GOALS_MANAGE_SELF,
    PERMISSIONS.DIRECT_CHAT_USE,
    PERMISSIONS.CALLS_USE,
    PERMISSIONS.INTERNSHIPS_READ_SELF,
    PERMISSIONS.TCC_READ_SELF,
    PERMISSIONS.LABORATORIES_READ,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.CERTIFICATES_READ,
  ]),
  responsavel: Object.freeze([
    PERMISSIONS.GUARDIAN_PORTAL_VIEW,
  ]),
  professor: Object.freeze([
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.GRADES_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.ASSIGNMENTS_WRITE,
    PERMISSIONS.CALENDAR_READ,
    PERMISSIONS.TEACHER_CALENDAR_VIEW,
    PERMISSIONS.SCHEDULES_RESPOND,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_WRITE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.OCCURRENCES_READ,
    PERMISSIONS.OCCURRENCES_WRITE,
    PERMISSIONS.DIARY_WRITE,
    PERMISSIONS.LESSON_PLANS_WRITE,
    PERMISSIONS.GOALS_READ_ALL,
    PERMISSIONS.TEACHER_PORTAL_VIEW,
    PERMISSIONS.ACADEMIC_RECORD_VIEW,
    PERMISSIONS.SUBMISSIONS_READ_ALL,
    PERMISSIONS.SUBMISSIONS_GRADE,
    PERMISSIONS.DIRECT_CHAT_USE,
    PERMISSIONS.CALLS_USE,
    PERMISSIONS.INTERNSHIPS_READ,
    PERMISSIONS.INTERNSHIPS_WRITE,
    PERMISSIONS.TCC_READ,
    PERMISSIONS.TCC_WRITE,
    PERMISSIONS.LABORATORIES_READ,
    PERMISSIONS.LABORATORIES_WRITE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_WRITE,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.CERTIFICATES_WRITE,
  ]),
  secretario: Object.freeze([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_WRITE,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.CLASSES_WRITE,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.CALENDAR_READ,
    PERMISSIONS.SCHEDULES_MANAGE,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_WRITE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_WRITE,
    PERMISSIONS.LIBRARY_LOANS_READ,
    PERMISSIONS.LIBRARY_LOANS_WRITE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.OCCURRENCES_READ,
    PERMISSIONS.OCCURRENCES_WRITE,
    PERMISSIONS.ACADEMIC_RECORD_VIEW,
    PERMISSIONS.REGISTRATION_VIEW,
    PERMISSIONS.ENROLLMENTS_MANAGE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.EVENTS_WRITE,
    PERMISSIONS.DIRECT_CHAT_USE,
    PERMISSIONS.CALLS_USE,
    PERMISSIONS.INTERNSHIPS_READ,
    PERMISSIONS.INTERNSHIPS_WRITE,
    PERMISSIONS.INTERNSHIP_COMPANIES_READ,
    PERMISSIONS.INTERNSHIP_COMPANIES_WRITE,
    PERMISSIONS.TCC_READ,
    PERMISSIONS.TCC_WRITE,
    PERMISSIONS.LABORATORIES_READ,
    PERMISSIONS.LABORATORIES_WRITE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_WRITE,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.CERTIFICATES_WRITE,
  ]),
  coordenador: Object.freeze([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_WRITE,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.TEACHERS_WRITE,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.CLASSES_WRITE,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.SUBJECTS_WRITE,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.GRADES_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.ASSIGNMENTS_WRITE,
    PERMISSIONS.CALENDAR_READ,
    PERMISSIONS.TEACHER_CALENDAR_VIEW,
    PERMISSIONS.TEACHER_CALENDAR_MANAGE_ALL,
    PERMISSIONS.SCHEDULES_MANAGE,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.SCHEDULES_PUBLISH,
    PERMISSIONS.SCHEDULES_AUDIT,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_WRITE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_LOANS_READ,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.OCCURRENCES_READ,
    PERMISSIONS.OCCURRENCES_WRITE,
    PERMISSIONS.DIARY_WRITE,
    PERMISSIONS.LESSON_PLANS_WRITE,
    PERMISSIONS.GOALS_READ_ALL,
    PERMISSIONS.TEACHER_PORTAL_VIEW,
    PERMISSIONS.ACADEMIC_RECORD_VIEW,
    PERMISSIONS.REGISTRATION_VIEW,
    PERMISSIONS.ENROLLMENTS_MANAGE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.USERS_MANAGE_ADMINISTRATIVE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.EVENTS_WRITE,
    PERMISSIONS.SUBMISSIONS_READ_ALL,
    PERMISSIONS.SUBMISSIONS_GRADE,
    PERMISSIONS.DIRECT_CHAT_USE,
    PERMISSIONS.CALLS_USE,
    PERMISSIONS.INTERNSHIPS_READ,
    PERMISSIONS.INTERNSHIPS_WRITE,
    PERMISSIONS.INTERNSHIP_COMPANIES_READ,
    PERMISSIONS.INTERNSHIP_COMPANIES_WRITE,
    PERMISSIONS.TCC_READ,
    PERMISSIONS.TCC_WRITE,
    PERMISSIONS.LABORATORIES_READ,
    PERMISSIONS.LABORATORIES_WRITE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_WRITE,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.CERTIFICATES_WRITE,
  ]),
  administrador: Object.freeze([
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_WRITE,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.TEACHERS_WRITE,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.CLASSES_WRITE,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.SUBJECTS_WRITE,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.GRADES_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.ASSIGNMENTS_WRITE,
    PERMISSIONS.CALENDAR_READ,
    PERMISSIONS.TEACHER_CALENDAR_VIEW,
    PERMISSIONS.TEACHER_CALENDAR_MANAGE_ALL,
    PERMISSIONS.SCHEDULES_MANAGE,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.SCHEDULES_PUBLISH,
    PERMISSIONS.SCHEDULES_AUDIT,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.MESSAGES_WRITE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.LIBRARY_WRITE,
    PERMISSIONS.LIBRARY_LOANS_READ,
    PERMISSIONS.LIBRARY_LOANS_WRITE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.OCCURRENCES_READ,
    PERMISSIONS.OCCURRENCES_WRITE,
    PERMISSIONS.DIARY_WRITE,
    PERMISSIONS.LESSON_PLANS_WRITE,
    PERMISSIONS.GOALS_READ_ALL,
    PERMISSIONS.TEACHER_PORTAL_VIEW,
    PERMISSIONS.ACADEMIC_RECORD_VIEW,
    PERMISSIONS.REGISTRATION_VIEW,
    PERMISSIONS.ENROLLMENTS_MANAGE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.USERS_MANAGE_ADMINISTRATIVE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.EVENTS_WRITE,
    PERMISSIONS.SUBMISSIONS_READ_ALL,
    PERMISSIONS.SUBMISSIONS_GRADE,
    PERMISSIONS.SYSTEM_EXPORT,
    PERMISSIONS.DIRECT_CHAT_USE,
    PERMISSIONS.CALLS_USE,
    PERMISSIONS.INTERNSHIPS_READ,
    PERMISSIONS.INTERNSHIPS_WRITE,
    PERMISSIONS.INTERNSHIP_COMPANIES_READ,
    PERMISSIONS.INTERNSHIP_COMPANIES_WRITE,
    PERMISSIONS.TCC_READ,
    PERMISSIONS.TCC_WRITE,
    PERMISSIONS.LABORATORIES_READ,
    PERMISSIONS.LABORATORIES_WRITE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_WRITE,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.CERTIFICATES_WRITE,
  ]),
});

const PAGE_PERMISSION_MATRIX = Object.freeze({
  Dashboard: [PERMISSIONS.DASHBOARD_VIEW],
  Students: [PERMISSIONS.STUDENTS_READ, PERMISSIONS.STUDENTS_READ_SELF],
  Teachers: [PERMISSIONS.TEACHERS_READ],
  Classes: [PERMISSIONS.CLASSES_READ],
  Subjects: [PERMISSIONS.SUBJECTS_READ],
  Grades: [PERMISSIONS.GRADES_READ],
  Attendance: [PERMISSIONS.ATTENDANCE_READ],
  Assignments: [PERMISSIONS.ASSIGNMENTS_READ],
  SchoolCalendar: [PERMISSIONS.CALENDAR_READ],
  TeacherCalendar: [PERMISSIONS.TEACHER_CALENDAR_VIEW],
  SchedulePlanner: [
    PERMISSIONS.SCHEDULES_MANAGE,
    PERMISSIONS.SCHEDULES_RESPOND,
    PERMISSIONS.SCHEDULES_VIEW,
    PERMISSIONS.SCHEDULES_PUBLISH,
    PERMISSIONS.SCHEDULES_AUDIT,
  ],
  Messages: [PERMISSIONS.MESSAGES_READ],
  Calls: [PERMISSIONS.CALLS_USE],
  LibraryPage: [PERMISSIONS.LIBRARY_READ],
  Reports: [PERMISSIONS.REPORTS_VIEW],
  Occurrences: [PERMISSIONS.OCCURRENCES_READ],
  Diary: [PERMISSIONS.DIARY_WRITE],
  StudentGoals: [PERMISSIONS.GOALS_MANAGE_SELF],
  GuardianPortal: [PERMISSIONS.GUARDIAN_PORTAL_VIEW],
  TeacherPortal: [PERMISSIONS.TEACHER_PORTAL_VIEW],
  AcademicRecord: [PERMISSIONS.ACADEMIC_RECORD_VIEW],
  TeacherHomework: [PERMISSIONS.ASSIGNMENTS_WRITE],
  StudentHomework: [PERMISSIONS.ASSIGNMENTS_READ],
  Registration: [PERMISSIONS.REGISTRATION_VIEW],
  StudentEnrollment: [PERMISSIONS.REGISTRATION_VIEW],
  UserManagement: [PERMISSIONS.USERS_MANAGE],
  SettingsPage: [PERMISSIONS.SETTINGS_READ],
  Internships: [PERMISSIONS.INTERNSHIPS_READ],
  InternshipCompanies: [PERMISSIONS.INTERNSHIP_COMPANIES_READ],
  InternshipDiary: [PERMISSIONS.INTERNSHIPS_READ],
  TCCProjects: [PERMISSIONS.TCC_READ],
  Laboratories: [PERMISSIONS.LABORATORIES_READ],
  Courses: [PERMISSIONS.COURSES_READ],
  Certificates: [PERMISSIONS.CERTIFICATES_READ],
  Desktop: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_READ_SELF,
    PERMISSIONS.TEACHERS_READ,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.CALENDAR_READ,
    PERMISSIONS.TEACHER_CALENDAR_VIEW,
    PERMISSIONS.SCHEDULES_MANAGE,
    PERMISSIONS.SCHEDULES_RESPOND,
    PERMISSIONS.MESSAGES_READ,
    PERMISSIONS.CALLS_USE,
    PERMISSIONS.LIBRARY_READ,
    PERMISSIONS.GUARDIAN_PORTAL_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.OCCURRENCES_READ,
    PERMISSIONS.DIARY_WRITE,
    PERMISSIONS.GOALS_MANAGE_SELF,
    PERMISSIONS.TEACHER_PORTAL_VIEW,
    PERMISSIONS.ACADEMIC_RECORD_VIEW,
    PERMISSIONS.REGISTRATION_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.INTERNSHIPS_READ,
    PERMISSIONS.INTERNSHIPS_READ_SELF,
    PERMISSIONS.INTERNSHIP_COMPANIES_READ,
    PERMISSIONS.TCC_READ,
    PERMISSIONS.TCC_READ_SELF,
    PERMISSIONS.LABORATORIES_READ,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.CERTIFICATES_READ,
  ],
});

export function getPermissionsForProfile(profileType) {
  return [...(ROLE_PERMISSION_MATRIX[profileType] || [])];
}

export function hasPermission(profileType, permission) {
  return getPermissionsForProfile(profileType).includes(permission);
}

export function hasAnyPermission(profileType, permissions = []) {
  if (!Array.isArray(permissions) || permissions.length === 0) {
    return true;
  }

  return permissions.some((permission) => hasPermission(profileType, permission));
}

export function isAdministrativeProfileType(profileType) {
  return ADMINISTRATIVE_PROFILE_TYPES.includes(profileType);
}

export function canAccessPage(profileType, pageName) {
  const requiredPermissions = PAGE_PERMISSION_MATRIX[pageName];
  if (!requiredPermissions) return false;
  if (requiredPermissions.length === 0) return true;
  return hasAnyPermission(profileType, requiredPermissions);
}

export function canAccessDashboard(profileType) {
  return hasPermission(profileType, PERMISSIONS.DASHBOARD_VIEW);
}

export function canWriteStudents(profileType) {
  return hasPermission(profileType, PERMISSIONS.STUDENTS_WRITE);
}

export function canWriteTeachers(profileType) {
  return hasPermission(profileType, PERMISSIONS.TEACHERS_WRITE);
}

export function canUseDirectChat(profileType) {
  return hasPermission(profileType, PERMISSIONS.DIRECT_CHAT_USE);
}

export function canManageUsers(profileType) {
  return hasPermission(profileType, PERMISSIONS.USERS_MANAGE);
}

export function canManageAdministrativeProfiles(profileType) {
  return hasPermission(profileType, PERMISSIONS.USERS_MANAGE_ADMINISTRATIVE);
}

export function canManageEnrollments(profileType) {
  return hasPermission(profileType, PERMISSIONS.ENROLLMENTS_MANAGE);
}

export function canCreateSystemUsers(profileType) {
  return canManageUsers(profileType);
}

export function canManageMessages(profileType) {
  return hasPermission(profileType, PERMISSIONS.MESSAGES_WRITE);
}

export function canCreateOwnClassMessages(profileType) {
  return hasPermission(profileType, PERMISSIONS.MESSAGES_WRITE_OWN_CLASS);
}

export function canManageAssignments(profileType) {
  return hasPermission(profileType, PERMISSIONS.ASSIGNMENTS_WRITE);
}

export function canWriteGrades(profileType) {
  return hasPermission(profileType, PERMISSIONS.GRADES_WRITE);
}

export function canWriteAttendance(profileType) {
  return hasPermission(profileType, PERMISSIONS.ATTENDANCE_WRITE);
}

export function canViewReports(profileType) {
  return hasPermission(profileType, PERMISSIONS.REPORTS_VIEW);
}

export function canViewTeacherPortal(profileType) {
  return hasPermission(profileType, PERMISSIONS.TEACHER_PORTAL_VIEW);
}

export function canExportSystemData(profileType) {
  return hasPermission(profileType, PERMISSIONS.SYSTEM_EXPORT);
}

export function canManageSchedules(profileType) {
  return hasPermission(profileType, PERMISSIONS.SCHEDULES_MANAGE);
}

export function canRespondScheduleAvailability(profileType) {
  return hasPermission(profileType, PERMISSIONS.SCHEDULES_RESPOND);
}
